### ISSUE TITLE
Tooling for WAT and WET file types

### ISSUE THREAD

**Issue by dinoDayo** [commoncrawl/ia-hadoop-tools#9]
Hey,

I am interested in writing a custom parser to support extracting WAT & WET properties from WARC files. 
Ideally, I would want the output of that parser to be compatible with the WAT & WET file formats CommonCrawl provides. 
[From what I have been able to find online](https://groups.google.com/g/common-crawl/c/hsb90GHq6to/m/SSVocyq8AAAJ), the logic CommonCrawl uses to extract WAT & WET properties from a given WARC file cannot be directly accessed. Are my assumptions about the parsing logic being obfuscated correct? If so, are there any external resources available to support developers interested in building tools for interacting with WebARChive data that are not dependent on Java?

Thanks a million for your time!

- Dayo

**Comment by wumpus** [comment]
Sorry, there's a miscommunication here.

Sebastian told you how you can run our tools and generate WAT and WET. These tools are public.

The thing you can't do is download WAT and WET from us -- we don't create them at all for CC-NEWS.

**Comment by dinoDayo** [comment]
Thanks for the response! 

I was not looking to download WAT/WET files, I am looking to replicate the logic Sebastian shared in other programming languages (Python instead of Java). 

The issue with that post is that [it references code that is already compiled Java.](https://github.com/commoncrawl/ia-hadoop-tools/blob/e5c89e834604e3ab3ae08a251f2c2d17449efedd/src/main/java/org/archive/hadoop/mapreduce/WATExtractorMapper.java#L21) This means I don't have a reference to the order of operations CC uses to generate a given WAT or WET file.

That being said the WAT & WET definitions seem relatively straightforward so I can probably approximate them without too much trouble. It's just nice to be sure, hence the request.

Thanks again.

**Comment by sebastian-nagel** [comment]
> it references code that is already compiled Java.

No. The Java source code is available and its compiled by Maven into a jar file:
- all code is in the project commoncrawl/ia-web-commons, esp. the class [ExtractingParseObserver](https://github.com/commoncrawl/ia-web-commons/blob/master/src/main/java/org/archive/resource/html/ExtractingParseObserver.java). It's also worth to take a look into the [corresponding unit tests](https://github.com/commoncrawl/ia-web-commons/blob/master/src/test/java/org/archive/resource/html/ExtractingParseObserverTest.java).
- the project commoncrawl/ia-hadoop-tools is not necessarily required, except you plan to scale up the conversion using Hadoop. See [here](https://groups.google.com/g/common-crawl/c/V7YhdygaNr8/m/Jr3_51JAAAAJ) about using ia-web-commons standalone.

There's nothing obfuscated, although I agree that the way it is implemented - based on the [observer pattern](https://en.wikipedia.org/wiki/Observer_pattern) - takes initially some time to understand.

**Comment by dinoDayo** [comment]
🤦 understood, apologies for the confusion. 
Thanks a million @sebastian-nagel & @wumpus!
